[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "client/dist"
  
  # Default build command - simplified for Netlify
  command = "cd client && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  VITE_API_URL = "https://ethioheritage360-ethiopian-heritage.onrender.com/api"
  VITE_USE_MOCK_API = "false"
  VITE_APP_NAME = "EthioHeritage360"
  VITE_SOCKET_URL = "https://ethioheritage360-ethiopian-heritage.onrender.com"

# Handle Socket.IO connections first (higher priority)
[[redirects]]
  from = "/socket.io/*"
  to = "https://ethioheritage360-ethiopian-heritage.onrender.com/socket.io/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "*", Access-Control-Allow-Headers = "*", Access-Control-Allow-Credentials = "true"}

# Redirect API calls to external backend on Render with proper CORS and timeout handling
[[redirects]]
  from = "/api/*"
  to = "https://ethioheritage360-ethiopian-heritage.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS,PATCH", Access-Control-Allow-Headers = "Content-Type,Authorization,X-Requested-With,Accept,Origin,Cache-Control,Pragma", X-Forwarded-For = "netlify", Access-Control-Allow-Credentials = "true"}

# Fallback for API calls that might timeout - redirect to wake up backend
[[redirects]]
  from = "/api/wake"
  to = "https://ethioheritage360-ethiopian-heritage.onrender.com/api/health"
  status = 200
  force = true

# Handle client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://ethioheritage360-ethiopian-heritage.onrender.com http://localhost:5000 https://api.mapbox.com https://events.mapbox.com wss: ws:;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[functions.environment]
  NODE_ENV = "production"
